[build.environment]
  NPM_FLAGS = "--version"
  NETLIFY_USE_PNPM = "true"
[build]
  command = "pnpm build"
  publish = "dist"
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/caramella-shortmovie"
  to = "/films/caramella/"
  status = 301

[[redirects]]
  from = "/caramella-shortmovie/"
  to = "/films/caramella/"
  status = 301

[[redirects]]
  from = "/filmmaker-journey"
  to = "/films/"
  status = 301

[[redirects]]
  from = "/filmmaker-journey/"
  to = "/films/"
  status = 301